name: Markdown Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Install markdownlint-cli
      run: npm install -g markdownlint-cli
    - name: Run markdownlint
      run: markdownlint '**/*.md'
